# config.yaml
openai_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"  # OpenAI API key, not used by crawler

# Used when writing the chunks to the database, not used by crawler
db_params:
  dbname: "xxxxxxxx"
  user: "xxxxxxxx"
  password: "XXXXXXXXXXX"
  host: "127.0.0.1"
  port: 0000

# Used to produce the final chatbot response, not used by crawler
openai_params:
  model: "gpt-4o"
  temperature: 0
  max_tokens: 1000
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  stop: null
